apiVersion: v1
description: Installs pihole in kubernetes
home: https://github.com/MoJo2600/pihole-kubernetes/tree/master/charts/pihole
name: pihole
appVersion: "2023.01"
version: 2.11.1
sources:
  - https://github.com/MoJo2600/pihole-kubernetes/tree/master/charts/pihole
  - https://pi-hole.net/
  - https://github.com/pi-hole
  - https://github.com/pi-hole/docker-pi-hole
icon: https://i2.wp.com/pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
maintainers:
  - name: MoJo2600
    email: christian.erhardt@mojo2k.de
