apiVersion: v1
description: Installs pihole in kubernetes
home: https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
name: pihole
appVersion: "2025.06.2"
# Do not touch will be updated during release
version: 2.32.0
sources:
  - https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
  - https://pi-hole.net/
  - https://github.com/pi-hole
  - https://github.com/pi-hole/docker-pi-hole
icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
maintainers:
  - name: MoJo2600
    email: christian.erhardt@mojo2k.de
