{{ if .Values.regex }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-regex
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
data:
  regex.list: |
  {{- range .Values.regex }}
    {{ . }}
  {{- end }}
{{ end }}
