{{ if .Values.whitelist }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-whitelist
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
data:
  whitelist.txt: |
  {{- range .Values.whitelist }}
    {{ . }}
  {{- end }}
{{ end }}
