{{ if .Values.dnsmasq.staticDhcpEntries }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-static-dhcp
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
data:
  pihole-static-dhcp.conf: |
  {{- range .Values.dnsmasq.staticDhcpEntries }}
    {{ . }}
  {{- end }}
{{ end }}
