{{ if .Values.denied }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-denied
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
data:
  blacklist.txt: |
  {{- range .Values.denied }}
    {{ . }}
  {{- end }}
{{ end }}
