{{- if and .Values.admin.enabled (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pihole.password-secret" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.admin.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.admin.password }}
  password: {{ .Values.admin.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end }}
