apiVersion: v1
kind: Service
metadata:
  name: {{ template "pihole.fullname" . }}-tcp
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceTCP.annotations }}
  annotations:
{{ toYaml .Values.serviceTCP.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceTCP.type }}
  {{- if .Values.serviceTCP.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceTCP.loadBalancerIP }}
  {{- end }}
  {{- if or (eq .Values.serviceUDP.type "NodePort") (eq .Values.serviceUDP.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceTCP.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
    - port: 53
      targetPort: dns
      protocol: TCP
      name: dns
  selector:
    app: {{ template "pihole.name" . }}
    release: {{ .Release.Name }}
